name: Upload to S3

on: [push]

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload-S3
      uses: shallwefootball/upload-s3-action@v1.3.3
      with:
        aws_key_id: ${{ secrets.AWS_S3_ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_KEY }}
        aws_bucket: cs293staticwebsite
        source_dir: https://github.com/tyang146/cs293securestaticwebsite.git
