# inside .github/workflows/action.yml
name: Add File to Bucket
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./index.html
          S3_ENDPOINT: 's3.amazonaws.com'
          S3_BUCKET: cs293staticwebsite
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
