- name: Upload S3
  # You may pin to the exact commit or the version.
  # uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e
  uses: shallwefootball/upload-s3-action@v1.3.3
  with:
    # aws key id
    aws_key_id: ${{ secrets.AWS_S3_ACCESS_KEY }}
    # aws secret access key
    aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_KEY }}
    # aws bucket name
    aws_bucket: cs293staticwebsite
    # directory to upload
    source_dir: https://github.com/tyang146/cs293securestaticwebsite.git
    # destination directory for upload
    destination_dir: # optional, default is /
    # endpoint URI to send requests
    endpoint: # optional
          
